pipeline {
    agent any
    stages {
        stage('build and push') {
            steps {
              sh ''' 
               cd docker
                docker build -t ravimanickavasagam/hello-java  .
                echo "8428077321" | docker login --username ravimanickavasagam --password-stdin
                docker push ravimanickavasagam/hello-java
                cd ..
              '''
            }
        }
        stage('deployment') {
            steps {
                sh ''' 
                    ansible-playbook ansible/main.yml
                '''
            }
        }

    }
}
