pipeline {
    agent any
    stages {
        stage('build and push') {
            steps {
              sh ''' 
               cd docker

                docker push ravimanickavasagam/hello-java
                cd ..
              '''
            }
        }
        stage('deployment') {
            steps {
                sh ''' 
                    ansible-playbook ansible/main.yml
                '''
            }
        }

    }
}
